In [1]:
!pip install pandas scikit-learn

Requirement already satisfied: pandas in d:\anaconda\lib\site-packages (2.2.2)
Requirement already satisfied: scikit-learn in d:\anaconda\lib\site-packages (1.5.1)
Requirement already satisfied: numpy>=1.26.0 in d:\anaconda\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: scipy>=1.6.0 in d:\anaconda\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in d:\anaconda\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\anaconda\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score

In [32]:
fake=pd.read_csv("F://Fake_News_Detection//Fake_small.csv")
true=pd.read_csv("F://Fake_News_Detection//true_small.csv")

In [33]:
#checking dataset
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [34]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [35]:
#labels 0-fake news,1-real news
fake['label']=0
true['label']=1

In [36]:
data=pd.concat([fake,true])

In [37]:
data['label'].value_counts()

label
0    1000
1    1000
Name: count, dtype: int64

In [38]:
x=data['text']
y=data['label']

In [39]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25,random_state=42)

In [40]:
vectorizer=TfidfVectorizer(stop_words="english")

In [41]:
x_train = vectorizer.fit_transform(x_train)
x_test = vectorizer.transform(x_test)

In [42]:
#Ai model
model=PassiveAggressiveClassifier(max_iter=50)

In [43]:
#train model
model.fit(x_train,y_train)

PassiveAggressiveClassifier(max_iter=50)

In [44]:
prediction=model.predict(x_test)

In [45]:
score = accuracy_score(y_test, prediction)
print("Accuracy:", score * 100)

Accuracy: 99.2